### ISSUE TITLE
Empty screen

### ISSUE THREAD

**Issue by sasikanth513** [shrihari/moviemonkey#3]
<img width="1279" alt="screen shot 2017-08-20 at 7 34 43 pm" src="https://user-images.githubusercontent.com/6153816/29495514-b39be6e0-85de-11e7-8e2c-a2a281f645e4.png">
Empty view in my macbook pro 13inch, is it bcz of my screen size or any other issues?

**Comment by shrihari** [comment]
@sasikanth513 No, this is not an issue. This is the empty screen. You'll have to add movies either by drag-and-drop or from File -> Import movies.

**Comment by sasikanth513** [comment]
My bad, I thought on first load it shows list from imdb or something. Thanks for quick response.

**Comment by sasikanth513** [comment]
@shrihari hey i'm trying to setup dev environment to contribute, I'm having issues, where can I ping you regarding those? or do you have time to respond these kind of issues?

**Comment by shrihari** [comment]
@sasikanth513 i'd love some help with development. What issue are you facing? You can ping me on [Facebook](http://facebook.com/shrihari).
